### ISSUE TITLE
savedInstanceState

### ISSUE THREAD

**Issue by bhaetsch** [bhaetsch/Frogger#10]
Du hast Recht, mit dem savedInstanceState kann man wohl die Activity fortsetzen, nachdem sie zerstört wurde. Ich werde mir das mal anschauen und versuchen es zu implementieren.
![basic-lifecycle-savestate](https://cloud.githubusercontent.com/assets/12293667/7931917/bb1349d4-0914-11e5-9e4c-af571d052898.png)

**Comment by bhaetsch** [comment]
Durch unseren MainThread ist das doch ziemlich komplex. savedInstanceState ist wohl nicht dafür gemacht, mit einem Hintergrund-Thread zu arbeiten. Der Thread blockiert wohl irgendwie den Ablauf des Lifecycles. onSaveIntanceState wird beim Verlassen zwar aufgerufen, aber beim Neuaufruf wird onCreate bzw. onRestoreInstanceState nicht aufgerufen. Dadurch hängt dann die Activity in einem inkonsistenten Zustand. Ich würde vorschlagen, dass wir uns das vielleicht am Ende nochmal anschauen, falls wir dann noch Lust und Zeit haben ;)

**Comment by sabbarotz** [comment]
ja

**Comment by bhaetsch** [comment]
Das scheint bei mir jetzt zu funktionieren, ohne dass ich irgendwas geändert habe. Ich mach Thema mal zu, irgendwie ist das Thema ja auf jeden Fall behandelt :D
