### ISSUE TITLE
master geaendert

### ISSUE THREAD

**Issue by sabbarotz** [bhaetsch/Frogger#3]
ja mist. jetzt hab ich die Files bei dir im master geaendert, da es mit Android Studio komliziert war. Ich hab aber sogut wie nichts ueberschrieben. Die app funktioniert auch bei mir.

**Comment by sabbarotz** [comment]
Muss man wohl seine eigene Fork haben und dann immer Pull request machen oder so.

**Comment by bhaetsch** [comment]
Du kannst auch ruhig den Master überschreiben. Dann müssen wir auch nicht immer gucken, welcher Branch grad der aktuelle ist. Ich habe grad mal die Anforderungen in eine txt-Datei gepackt und die hier mit hochgeladen. Liegt unter .../res/values
